package kr.co.local_pick.local_pick.enums;

public enum Region {
    SEOUL, INCHEON, DAEJEON, DAEGU, ULSAN, BUSAN, GWANGJU, SEJONG,
    GYEONGGI, GANGWON, CHUNGCHEONGNAM, CHUNGCHEONGBUK, JEOLLANAM, JEOLLABUK,
    GYEONGSANGNAM, GYEONGSANGBUK, JEJU
}
